format_version: 3
pipelines:
  Test-REPO1-release:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/siddhi1907/Test-REPO1.git
        shallow_clone: false
        auto_update: true
        branch: master
    parameters:
      BRANCH: master
      VERSION: '1.0'
    template: testing-pipelines-1.2
